/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    ArticleList: typeof import('./../components/ArticleList.vue')['default']
    ArticleListItem: typeof import('./../components/ArticleListItem.vue')['default']
    ArticleRenderer: typeof import('./../components/ArticleRenderer.vue')['default']
    ArticleToc: typeof import('./../components/content/ArticleToc.vue')['default']
    ImageViewer: typeof import('./../components/content/ImageViewer.vue')['default']
    LinkCard: typeof import('./../components/content/LinkCard.vue')['default']
    PageNavigator: typeof import('./../components/PageNavigator.vue')['default']
    TextWithVerification: typeof import('./../components/content/TextWithVerification.vue')['default']
  }
}
