name: Deploy on content-updated

on:
  repository_dispatch:
    types: [content-updated]

permissions: {}

jobs:
  invoke_deployment:
    permissions:
      contents: read

    uses: ./.github/workflows/deploy.yml

    secrets: inherit
