name: Deploy on PR comment

on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  invoke_deployment:
    permissions:
      contents: read

    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '/preview' && github.event.comment.user.login == github.repository_owner }}

    uses: ./.github/workflows/deploy.yml
    with:
      ref: refs/pull/${{ github.event.issue.number }}/merge

    secrets: inherit

  comment_workflow_url:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '/preview' && github.event.comment.user.login == github.repository_owner }}

    outputs:
      comment_id: ${{ steps.comment.outputs.result }}

    steps:
      - name: Comment workflow url
        id: comment
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        with:
          result-encoding: string
          script: |
            const res = await github.rest.issues.createComment({
              ...context.repo,
              issue_number: process.env.ISSUE_NUMBER,
              body: `Deployment is ongoing.\n\nCheck logs at https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
            return res.data.id;
  
  comment_deployment_success:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    needs: [comment_workflow_url, invoke_deployment]

    steps:
      - name: Comment deployment success
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ needs.comment_workflow_url.outputs.comment_id }}
        with:
          script: |
            await github.rest.issues.updateComment({
              ...context.repo,
              comment_id: process.env.COMMENT_ID,
              body: `Deployment is ongoing.\n\nCheck logs at https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${context.runId}\n\nDeployment successfully finished.`
            });

  comment_deployment_failure:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    needs: [comment_workflow_url, invoke_deployment]

    if: ${{ always() && needs.comment_workflow_url.result == 'success' && needs.invoke_deployment.result == 'failure' }}

    steps:
      - name: Comment deployment failure
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ needs.comment_workflow_url.outputs.comment_id }}
        with:
          script: |
            await github.rest.issues.updateComment({
              ...context.repo,
              comment_id: process.env.COMMENT_ID,
              body: `Deployment is ongoing.\n\nCheck logs at https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${context.runId}\n\nDeployment failed.`
            });
