name: Deploy

on:
  workflow_dispatch:
  workflow_call:
  issue_comment:
    types: [created]

permissions: {}

env:
  NODE_ENV: production

jobs:
  decide_environment:
    runs-on: ubuntu-latest

    steps:
      - id: get_env
        run: echo "environment=$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo Production; else echo Preview; fi)" >> $GITHUB_OUTPUT

    outputs:
      environment: ${{ steps.get_env.outputs.environment }}

  check_request_validity:
    runs-on: ubuntu-latest

    steps:
      - id: check_validity
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: echo "is_valid=$(if [ '${{ github.event_name }}' == 'workflow_dispatch' ]; then echo true; elif [ '${{ github.event_name }}' == 'workflow_call' ]; then echo true; elif [ '${{ github.event_name }}' == 'issue_comment' ] && [ '${{ github.event.comment.user.login }}' == '${{ github.repository_owner }}' ] && [ "$COMMENT_BODY" == '/preview' ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT

    outputs:
      is_valid: ${{ steps.check_validity.outputs.is_valid }}

  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    needs: [decide_environment, check_request_validity]

    environment: ${{ needs.decide_environment.outputs.environment }}

    if: needs.check_request_validity.outputs.is_valid == 'true'

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: corepack enable
      - name: Get GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CONTENT_READ_APP_ID }}
          private-key: ${{ secrets.CONTENT_READ_APP_PRIVATE_KEY }}
          owner: ${{ secrets.CONTENT_REPO_OWNER }}
          repositories: |
            ${{ secrets.CONTENT_REPO_NAME }}
      - name: Clone content repository
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ secrets.CONTENT_REPO_OWNER }}/${{ secrets.CONTENT_REPO_NAME }}
          path: content_repo
          token: ${{ steps.app-token.outputs.token }}
      - name: Move content directory
        run: mv ./content_repo/content ./
      - name: Clean content repository
        run: rm -rf ./content_repo
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build > /dev/null
      - name: Post build
        run: pnpm run post-build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          quiet: true
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
