name: Lost Pixel

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

env:
  LOST_PIXEL_DISABLE_TELEMETRY: 1

jobs:
  lost-pixel:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          path: latest
          sparse-checkout: |
            .lostpixel-baseline
      - name: Get baseline ref
        id: get-baseline-ref
        run: |
          echo "ref=$(cat latest/.lostpixel-baseline)" >> $env:GITHUB_OUTPUT
          rm -rf ./latest
      - name: Checkout (baseline)
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-baseline-ref.outputs.ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Get playwright version
        id: get-playwright-version
        run: |
          echo "version=$(pnpm list --depth 1 --json | cat | jq -r '.[0].devDependencies."lost-pixel".dependencies."playwright-core".version')" >> $env:GITHUB_OUTPUT
      - name: Cache playwright browsers
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ steps.get-playwright-version.outputs.version }}-chromium
      - name: Install playwright browsers
        if: ${{ steps.cache-playwright-browsers.outputs.cache-hit != 'true' }}
        env:
          PLAYWRIGHT_VERSION: ${{ steps.get-playwright-version.outputs.version }}
        run: |
          pnpx playwright@$env:PLAYWRIGHT_VERSION install chromium --with-deps
      - name: Build story (baseline)
        run: pnpm run story:build
      - name: Lost Pixel (baseline)
        run: pnpm lost-pixel
        env:
          LOST_PIXEL_MODE: update
      - name: Upload artifact (baseline)
        id: upload-baseline
        uses: actions/upload-artifact@v4
        with:
          name: lost-pixel-baseline
          path: |
            .lostpixel/baseline

      - uses: actions/checkout@v4
      - run: pnpm install --frozen-lockfile
      - name: Build story (head)
        run: pnpm run story:build
      - name: Download baseline from artifact
        id: download-baseline
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ steps.upload-baseline.outputs.artifact-id }}
      - name: Move baseline files
        env:
          DOWNLOAD_PATH: ${{ steps.download-baseline.outputs.download-path }}
        run: |
          mkdir .lostpixel
          mv "$DOWNLOAD_PATH/lost-pixel-baseline" ./.lostpixel/baseline
      - name: Lost Pixel (head)
        id: lost-pixel-head
        run: pnpm lost-pixel
      - name: Fail if story disappeared
        uses: actions/github-script@v7
        with:
          script: |
            const { interpret } = require('./scripts/interpret-lost-pixel-result.js');
            const { dissappearedImages } = interpret();
            if (dissappearedImages.length > 0) {
              core.setFailed('Possible removed stories detected.');
            }
      - name: Upload artifact (head)
        if: ${{ always() && steps.lost-pixel-head.outcome != 'cancelled' && steps.lost-pixel-head.outcome != 'skipped' }}
        uses: actions/upload-artifact@v4
        with:
          name: lost-pixel-result
          path: |
            .lostpixel/baseline
            .lostpixel/current
            .lostpixel/difference
      - name: Comment stories with differences
        if: ${{ always() && github.event.pull_request && steps.lost-pixel-head.outcome != 'cancelled' && steps.lost-pixel-head.outcome != 'skipped' }}
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          script: |
            const { interpretAndMarkup } = require('./scripts/interpret-lost-pixel-result.js');
            const markup = interpretAndMarkup();
            const content = `### Lost Pixel Result\n\n${markup}`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: process.env.PR_NUMBER,
              body: content,
            });
